POST http://localhost:3000/cursos/programacion

###

PUT http://localhost:3000/ HTTP/1.1

###

GET http://localhost:3000/ HTTP/1.1

###

POST http://localhost:3000/cursos/programacion
Content-Type: application/json
{
    "titulo":"Aprende lo que sea";
}