POST http://localhost:3000/api/cursos/programacion HTTP/1.1
Content-Type: application/json

{
  "id": 5,
  "titulo": "Aprende Node.js",
  "lenguaje": "javascript",
  "vistas":344523,
  "nivel": "basico"
}

###
PUT http://localhost:3000/api/cursos/programacion/3 HTTP/1.1
Content-Type: application/json

{
    "id": 3,
    "titulo": "Aprende java",
    "lenguaje": "java",
    "vistas": 12000,
    "nivel": "intermedio"
}

###
PATCH http://localhost:3000/api/cursos/programacion/3 HTTP/1.1
Content-Type: application/json

{
  "lenguaje":"java"
}

###
DELETE http://localhost:3000/api/cursos/programacion/1 HTTP/1.1
